"use strict";

const fs=require("fs"),crypto=require("crypto"),Base=require("./commerce-candidate-registry-sync.baseline-1229.v1"),Pipeline=require("./commerce-product-pipeline-state.v1"),ProductRanking=require("./commerce-product-ranking.v1");
const VERSION="commerce-candidate-registry-sync-v1.17.0-admin-board-structural-only";
function t(v){return v==null?"":String(v).trim()}function l(v){return t(v).toLowerCase()}function o(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}}function a(v){return Array.isArray(v)?v:[]}function f(){for(const v of arguments){const x=t(v);if(x)return x}return""}function https(v){try{const u=new URL(t(v));return u.protocol==="https:"?u.toString():""}catch(_e){return""}}function now(){return new Date().toISOString()}function sha(v){return crypto.createHash("sha256").update(v).digest("hex")}
const FRONT_SECTIONS=new Set([
"home|home_1","home|home_2","home|home_3","home|home_4","home|home_5","home|home_6","home|home_right_top","home|home_right_middle","home|home_right_bottom",
"distribution|distribution-recommend","distribution|distribution-sponsor","distribution|distribution-trending","distribution|distribution-new","distribution|distribution-special","distribution|distribution-others","distribution|distribution-extra","distribution|distribution-right",
"network|network-right","social|rightPanel","tour|tour"
]);
function requested(row){const r=o(row&&row.publicationRequest),s=l(o(row&&row.assignment).publicationStatus);return r.requested===true||l(r.status)==="publish_requested"||["publish_requested","matched","published"].includes(s)}
function productAssetUrl(v){try{return /\.(?:avif|bmp|gif|ico|jpe?g|png|svg|webp)(?:$|[?#])/i.test(new URL(t(v)).pathname)}catch(_e){return false}}
function normalize(row){
 const out=JSON.parse(JSON.stringify(row||{})),c=o(out.candidate),r=o(out.publicationRequest),as=o(out.assignment),p=o(c.approvedPlacement||c.selectedPlacement||c.primaryPlacement||c.placement),rec=Pipeline.administratorProductRecord(c)||{},card=o(o(c.researchReadiness).productCard),pc=o(c.productCard);
 const id=t(c.id),title=f(rec.title,pc.title,card.title,c.productName,c.title),url=https(f(rec.productUrl,c.externalProductUrl,c.officialProductUrl,c.productUrl,c.productPageUrl,pc.productUrl,card.productUrl,c.detailUrl,c.checkoutUrl,c.url,c.link,c.href)),image=https(f(rec.imageUrl,pc.imageUrl,pc.imageOriginalUrl,pc.thumbnailUrl,pc.thumbnail,pc.image,card.imageUrl,card.thumbnailUrl,card.thumbnail,card.image,c.imageUrl,c.thumbnailUrl,c.thumbnail,c.image)),page=f(r.page,as.page,p.page,c.page,c.channel),section=f(r.section,as.section,p.sectionKey,p.section,c.section,c.psom_key),country=f(r.country,as.country,p.country,c.country,c.targetCountry).toUpperCase(),region=f(r.region,as.region,p.region,c.region,"NATIONWIDE").toUpperCase()||"NATIONWIDE",assignmentId=f(r.assignmentId,as.id),stamp=f(as.updatedAt,r.requestedAt,now()),errors=[];
 if(!id)errors.push("candidate_id_missing");if(!title)errors.push("title_missing");if(!url)errors.push("product_url_missing_or_not_https");else if(productAssetUrl(url))errors.push("product_url_is_image_asset");if(!image)errors.push("image_missing_or_not_https");if(!page)errors.push("page_missing");if(!section)errors.push("section_missing");if(page&&section&&!FRONT_SECTIONS.has(page+"|"+section))errors.push("invalid_front_section");if(!country)errors.push("country_missing");if(!assignmentId)errors.push("assignment_id_missing");
 const req=Object.assign({},r,{requested:true,status:"publish_requested",assignmentId,requestedAt:f(r.requestedAt,stamp),requestedBy:f(r.requestedBy,as.updatedBy,"administrator"),country,region,page,section,crossCountryFallback:false});
 const auth={schema:"igdc-administrator-front-match-authority.v1",verified:true,assignmentId,publicationStatus:"publish_requested",page,section,country,region,externalSeller:true,noIgdcCheckout:true,noIgdcPayment:true,verifiedAt:stamp,verificationSource:"administrator-20-section-master-board"};
 out.candidate=Object.assign({},c,{id,title,name:title,url,link:url,href:url,externalProductUrl:url,officialProductUrl:f(c.officialProductUrl,url),productUrl:url,productPageUrl:url,detailUrl:url,checkoutUrl:url,image,imageUrl:image,thumb:image,thumbnail:image,thumbnailUrl:image,page,channel:page,route:page,section,psom_key:section,slotKey:section,placement:Object.assign({},o(c.placement),{page,section,sectionKey:section,country,region}),approvedPlacement:Object.assign({},o(c.approvedPlacement),{page,section,sectionKey:section,country,region,manualPinned:as.state==="pinned"}),administratorFrontMatchAuthority:auth,commerceReview:Object.assign({},o(c.commerceReview),{status:"approved",assignmentState:as.state==="pinned"?"pinned":"approved",approvalId:assignmentId,approvedAt:stamp,publicationStatus:"publish_requested",explicitPublicationRequested:true,publicationRequest:req}),commerceCandidate:Object.assign({},o(c.commerceCandidate),{sourceTier:"approved_commerce_member",origin:"admin_review_queue",explicitPublicationRequested:true,publicationScope:{country,region,page,section,crossCountryFallback:false}}),directCommerceListing:Object.assign({},o(c.directCommerceListing),{sourceTier:"approved_commerce_member"}),searchBankContract:Object.assign({},o(c.searchBankContract),{frontSupplyAllowed:true,searchBankEligible:true,snapshotEligible:true,indexEligible:true,lastVerifiedAt:stamp,officialSource:true,producerVerified:true}),frontBridgeValidation:{version:VERSION,structuralOnly:true,ok:errors.length===0,errors}});
 out.sourceTier="approved_commerce_member";out.assignment=Object.assign({},as,{id:assignmentId,state:as.state==="pinned"?"pinned":"approved",page,section,country,region,publicationStatus:"publish_requested",updatedAt:stamp});out.publicationRequest=req;out.review=Object.assign({},o(out.review),{status:"approved",assignmentState:out.assignment.state,approvalId:assignmentId,approvedAt:stamp});out.bridgeValidation={ok:errors.length===0,structuralOnly:true,errors};return out;
}
async function syncApprovedCandidates(input){
 const res=await Base.syncApprovedCandidates(input);if(!res||res.wrote!==true||!res.file||!fs.existsSync(res.file))return Object.assign({},res||{},{version:VERSION});
 let doc;try{doc=JSON.parse(fs.readFileSync(res.file,"utf8"))}catch(e){return Object.assign({},res,{ok:false,status:"blocked",version:VERSION,reason:"front_bridge_queue_read_failed",error:t(e&&e.message)})}
 doc.items=a(doc.items).map(x=>requested(x)?normalize(x):x);const req=doc.items.filter(requested),bad=req.filter(x=>o(x.bridgeValidation).ok!==true),scope=Array.from(new Set(req.map(x=>{const r=o(x.publicationRequest);return t(r.country)?t(r.country).toUpperCase()+"|"+(t(r.region).toUpperCase()||"NATIONWIDE"):""}).filter(Boolean))),auth=Object.assign({},o(doc.releaseAuthorization),{authoritative:req.length>0||o(doc.releaseAuthorization).explicitAdminWithdrawal===true,mode:req.length?"explicit-admin-publication-request":o(doc.releaseAuthorization).mode,explicitAdminRequest:req.length>0,requestedCount:req.length,scopeKeys:scope,source:"administrator-20-section-master-board",generatedAt:now(),crossCountryFallback:false,automaticPublication:false});
 doc.version=VERSION;doc.generatedAt=now();doc.authoritative=auth.authoritative;doc.explicitAdminRequest=auth.explicitAdminRequest;doc.requestedCount=req.length;doc.scopeKeys=scope;doc.releaseAuthorization=auth;doc.bridge={schema:"igdc-admin-board-searchbank-handoff.v1",version:VERSION,structuralOnlyAfterBoard:true,policyRejudgement:false,manualPlacementAuthority:true,requested:req.length,structurallyValid:req.length-bad.length,structuralErrors:bad.map(x=>({candidateId:t(o(x.candidate).id)||null,errors:a(o(x.bridgeValidation).errors)})).slice(0,100)};
 const body=JSON.stringify(doc,null,2)+"\n",tmp=res.file+"."+process.pid+".frontbridge.tmp";fs.writeFileSync(tmp,body,"utf8");fs.renameSync(tmp,res.file);return Object.assign({},res,{version:VERSION,digest:sha(body),count:doc.items.length,requestedCount:req.length,scopeKeys:scope,authoritative:auth.authoritative,releaseAuthorization:auth,bridge:doc.bridge});
}
module.exports=Object.assign({},Base,{VERSION,syncApprovedCandidates,normalizeRequestedEntry:normalize});
