"use strict";
/** Regional country front-supply gate. Explicit front supply only. */
const CountryPolicy = require("./regional-brokerage-policy.core.v1");
const VERSION = "regional-brokerage-front-supply-gate-core-v1.0";
function text(v){return v==null?"":String(v).trim();} function lower(v){return text(v).toLowerCase();} function asArray(v){return Array.isArray(v)?v:(v==null||v===""?[]:[v]);} function firstValue(){for(const v of arguments){const o=text(v);if(o)return o;}return "";} function nested(o,p){let c=o;for(const k of p){if(!c||typeof c!=="object"||!(k in c))return undefined;c=c[k];}return c;}
function candidateId(item,index){return firstValue(item&&item.id,item&&item.contentId,item&&item.productId,item&&item.url,item&&item.link,item&&item.title,"country-supply-"+String(index==null?"item":index));}
function numericScore(item){for(const v of [item&&item.frontSupplyScore,item&&item.score,item&&item.priority,nested(item,["rank","score"]),nested(item,["trust","score"]),nested(item,["sanmaruTrust","score"])]){const n=Number(v);if(Number.isFinite(n))return n;}return 0;}
function hubOf(context){return lower(firstValue(context&&context.hub,context&&context.pageName,context&&context.page,context&&context.channel,context&&context.section,"default"))||"default";}
function sourceText(item){item=item||{};return lower([item.page,item.channel,item.route,item.type,item.category,item.section,item.psom_key,item.slotKey,item.platform,item.provider,item.source,nested(item,["bind","page"]),nested(item,["bind","section"]),...(Array.isArray(item.tags)?item.tags:[])].filter(Boolean).join(" "));}
function matchesHub(item,hub){const t=sourceText(item);if(!t)return true;if(hub==="home")return /home|distribution|social|front|slot/.test(t);if(hub==="distribution")return /distribution|commerce|product|shop|market|buy|seller|supplier/.test(t);if(hub==="media")return /media|video|movie|drama|film|youtube|vimeo|tiktok|shorts|music/.test(t);if(hub==="social")return /social|instagram|youtube|tiktok|facebook|wechat|weibo|pinterest|reddit|twitter|x-/.test(t);if(hub==="network")return /network|networkhub/.test(t);if(hub==="tour")return /tour|travel|tourism|hotel|trip|flight|여행|관광/.test(t);if(hub==="donation")return /donation|donate|ngo|charity|relief|mission|후원|기부/.test(t);return true;}
function policyMarket(policy,market){const code=CountryPolicy.normalizeCountry(market);const markets=policy&&policy.markets&&typeof policy.markets==="object"?policy.markets:{};return markets[code]||markets[String(code).toLowerCase()]||markets[String(code).toUpperCase()]||{};}
function bool(v){if(v===true)return true;if(v===false||v==null)return false;return !["","0","false","no","off","disabled","disable"].includes(lower(v));}
function snapshotPublishingEnabled(targetMarket,policy){const resolved=policy&&typeof policy==="object"?policy:CountryPolicy.loadPolicy();const defaults=resolved&&resolved.defaults||{};const selected=policyMarket(resolved,targetMarket);if(Object.prototype.hasOwnProperty.call(selected,"snapshotPublishing"))return bool(selected.snapshotPublishing);if(Object.prototype.hasOwnProperty.call(defaults,"snapshotPublishing"))return bool(defaults.snapshotPublishing);return true;}
function minimumSnapshotCandidates(targetMarket,hub,policy){const p=policy&&typeof policy==="object"?policy:CountryPolicy.loadPolicy();const selected=policyMarket(p,targetMarket);const d=p.defaults||{};const src=selected.minimumPublishCandidates||selected.minimumCountrySnapshotCandidates||d.minimumPublishCandidates||{default:1};const raw=src&&typeof src==="object"?(src[hub]||src.default||1):src;const n=Number(raw);return Number.isFinite(n)&&n>0?Math.floor(n):1;}
function minimumRegionalCandidates(targetMarket,hub,policy){const p=policy&&typeof policy==="object"?policy:CountryPolicy.loadPolicy();const selected=policyMarket(p,targetMarket);const d=p.defaults||{};const src=selected.minimumRegionalCandidates||d.minimumRegionalCandidates||{default:1};const raw=src&&typeof src==="object"?(src[hub]||src.default||1):src;const n=Number(raw);return Number.isFinite(n)&&n>0?Math.floor(n):1;}
function normalizePublicDecision(v){v=v||{};return {targetMarket:v.targetMarket||null,targetRegion:v.targetRegion||null,sourceCountry:v.sourceCountry||null,sourceCountryEvidence:v.sourceCountryEvidence||null,sourceCountryVerified:v.sourceCountryVerified===true,distributionMarketCountry:v.distributionMarketCountry||v.sourceCountry||null,distributionMarketEvidence:v.distributionMarketEvidence||v.sourceCountryEvidence||null,distributionMarketVerified:v.distributionMarketVerified===true||v.sourceCountryVerified===true,distributionMarketRegion:v.distributionMarketRegion||null,distributionMarketRegionEvidence:v.distributionMarketRegionEvidence||null,originCountry:v.originCountry||null,originCountryEvidence:v.originCountryEvidence||null,availabilityCountries:Array.isArray(v.availabilityCountries)?v.availabilityCountries.slice():[],availabilityEvidence:Array.isArray(v.availabilityEvidence)?v.availabilityEvidence.slice():[],availabilityRegions:Array.isArray(v.availabilityRegions)?v.availabilityRegions.slice():[],availabilityRegionEvidence:Array.isArray(v.availabilityRegionEvidence)?v.availabilityRegionEvidence.slice():[],nationalAvailability:v.nationalAvailability===true,localResponsibilityEvidence:Array.isArray(v.localResponsibilityEvidence)?v.localResponsibilityEvidence.slice():[],supplierVerified:v.supplierVerified===true,supplierTrustEvidence:Array.isArray(v.supplierTrustEvidence)?v.supplierTrustEvidence.slice():[],existingTrustBlocked:v.existingTrustBlocked===true,localResponsibilityVerified:v.localResponsibilityVerified===true,externalSellerUrl:v.externalSellerUrl||null,externalSellerHost:v.externalSellerHost||null,largeMarketplace:v.largeMarketplace===true,supplyTier:v.supplyTier||"unknown",supplyTierOrder:Number.isFinite(Number(v.supplyTierOrder))?Number(v.supplyTierOrder):999,approvedSourceMarket:v.approvedSourceMarket===true,wouldAllowFrontSupply:v.wouldAllowFrontSupply===true,frontSupplyAllowed:v.frontSupplyAllowed===true,readiness:v.readiness||"unknown",reasons:Array.isArray(v.reasons)?v.reasons.slice():[],policyVersion:v.policyVersion||null,enforcement:v.enforcement||"audit"};}
function buildSelection(items,context){context=context||{};const targetMarket=CountryPolicy.resolveTargetMarket(context);const targetRegion=CountryPolicy.resolveTargetRegion(context);const hub=hubOf(context);const policy=context.policy&&typeof context.policy==="object"?context.policy:CountryPolicy.loadPolicy();const baseEligible=typeof context.baseEligible==="function"?context.baseEligible:(()=>true);const scoped=asArray(items).filter(x=>x&&typeof x==="object"&&baseEligible(x)&&matchesHub(x,hub));const local=CountryPolicy.normalizeCountry(targetMarket);const localCount=scoped.filter(i=>CountryPolicy.distributionMarketEvidence(i).country===local).length;const regionalCount=targetRegion?scoped.filter(i=>{const c=CountryPolicy.distributionMarketEvidence(i).country;const r=CountryPolicy.distributionRegionEvidence(i,c).region;const a=CountryPolicy.regionalAvailabilityEvidence(i,c);return c===local&&(r===targetRegion||a.regions.includes(targetRegion));}).length:0;const plan=CountryPolicy.resolveSupplyPlan({targetMarket,targetRegion,hub,policy,localCandidateCount:localCount,regionalCandidateCount:regionalCount});const evaluated=scoped.map((item,index)=>{const decision=CountryPolicy.evaluateCandidateForTarget(item,{targetMarket:plan.targetMarket,targetRegion:plan.targetRegion,hub,policy,plan,localCandidateCount:localCount,regionalCandidateCount:regionalCount});return{item,index,id:candidateId(item,index),decision:normalizePublicDecision(decision)};});const accepted=evaluated.filter(e=>e.decision.wouldAllowFrontSupply);const held=evaluated.filter(e=>!e.decision.wouldAllowFrontSupply);accepted.sort((a,b)=>a.decision.supplyTierOrder-b.decision.supplyTierOrder||numericScore(b.item)-numericScore(a.item)||a.index-b.index);const reasons={};for(const e of held)for(const r of e.decision.reasons.length?e.decision.reasons:["COUNTRY_POLICY_HOLD"])reasons[r]=(reasons[r]||0)+1;const byTier={};for(const e of accepted){const k=e.decision.supplyTier||"unknown";byTier[k]=(byTier[k]||0)+1;}return{version:VERSION,targetMarket:plan.targetMarket,targetRegion:plan.targetRegion||null,hub,plan,enforcement:plan.enforcement,eligibleInputCount:scoped.length,accepted,held,acceptedItems:accepted.map(e=>e.item),heldItems:held.map(e=>e.item),decisionsById:new Map(evaluated.map(e=>[e.id,e.decision])),audit:{targetMarket:plan.targetMarket,targetRegion:plan.targetRegion||null,hub,policyVersion:plan.policyVersion,enforcement:plan.enforcement,localCandidateCount:localCount,regionalCandidateCount:regionalCount,minimumLocalCandidates:plan.minimumLocalCandidates,minimumRegionalCandidates:plan.minimumRegionalCandidates,localShortage:plan.localShortage,regionalShortage:plan.regionalShortage,acceptedCount:accepted.length,heldCount:held.length,acceptedByTier:byTier,heldByReason:reasons}};}
function decisionForCandidate(item,selection,context){if(!selection||!selection.plan)return null;const known=selection.decisionsById&&selection.decisionsById.get(candidateId(item));if(known)return known;return normalizePublicDecision(CountryPolicy.evaluateCandidateForTarget(item,{targetMarket:selection.plan.targetMarket,targetRegion:selection.plan.targetRegion,hub:selection.hub||hubOf(context),plan:selection.plan,localCandidateCount:selection.plan.localCandidateCount,regionalCandidateCount:selection.plan.regionalCandidateCount}));}
function selectItems(items,context){const selection=buildSelection(items,context);const enforced=context&&context.forceEnforce===true||selection.enforcement==="enforce";return Object.assign(selection,{enforced,items:enforced?selection.acceptedItems:asArray(items)});}
module.exports={version:VERSION,matchesHub,snapshotPublishingEnabled,minimumSnapshotCandidates,minimumRegionalCandidates,buildSelection,decisionForCandidate,selectItems,normalizePublicDecision};
